# Assignment - 2

In [1]:
import numpy as np

## 1. Create a NumPy array containing integers from 0 to 9.

In [2]:
arr1= np.arange(0,10)
arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## 2. Create a NumPy array from a given Python list [10, 20, 30, 40, 50].

In [3]:
arr2=np.array([10,20,30,40,50])
arr2

array([10, 20, 30, 40, 50])

### 3. Create a 2D array (3x3) with values ranging from 0 to 8.

In [4]:
arr3=np.arange(0,9).reshape(3,3)
arr3

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

### 4. Given a 2D array, find its shape and size. Create a 5x4 array with random integers between 1 and 100, and print the shape and size.

In [5]:
arr4=np.random.randint(1,100,20).reshape(5,4)
arr4

array([[62, 43, 65, 79],
       [64, 71, 78, 15],
       [24, 89, 90, 10],
       [ 7, 59, 72, 78],
       [75, 50, 40, 36]], dtype=int32)

### 5. Create a 3x3 array of integers and access:

In [6]:
arr5=np.arange(0,9).reshape(3,3)
arr5

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### a. The second element of the first row.

In [7]:
arr5[0,1]

np.int64(1)

#### b. The third column of the 2nd row.

In [8]:
arr5[1,2]

np.int64(5)

#### c. A subarray with the first two rows and last two columns.

In [9]:
arr5_a=arr5[0:2, 1:]
arr5_a

array([[1, 2],
       [4, 5]])

### 6. Create a 1D array of 12 elements. Reshape it into a 3x4 2D array.

In [10]:
arr6=np.arange(0,12)
arr6_a=arr6.reshape(3,4)
arr6_a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

### 7. Reshape a 3x3 matrix into a 1D array.

In [11]:
arr7=np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16])
arr7_a=arr7.reshape(4,4)
arr7_a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

### 8. Create two arrays of shape (2, 3): arr1 and arr2.

In [12]:
arr1=np.array([[1,2],
               [3,4]]) 
arr2= np.array([[9,8],
                [7,6]])

#### a. Perform element-wise addition.

In [13]:
add=arr1+arr2
add

array([[10, 10],
       [10, 10]])

#### b. Perform element-wise subtraction.

In [14]:
sub=arr2-arr1
sub

array([[8, 6],
       [4, 2]])

#### c. Perform element-wise multiplication on them.

In [15]:
mult=arr1* arr2
mult

array([[ 9, 16],
       [21, 24]])

#### d. Perform element-wise division on them.

In [16]:
div=arr1/arr2
div

array([[0.11111111, 0.25      ],
       [0.42857143, 0.66666667]])

### 9. Use NumPy's built-in functions to compute following.

In [17]:
arr9=np.array([[1,2],
               [3,4]]) 

#### a. sum of a given array.

In [18]:
arr_sum=np.sum(arr9)
arr_sum

np.int64(10)

#### b. mean of a given array.

In [19]:
arr_mean=np.mean(arr9)
arr_mean

np.float64(2.5)

#### c. standard deviation of a given array.

In [20]:
arr_std=np.std(arr9)
arr_std

np.float64(1.118033988749895)

### 10. Create a 2x2 matrix A and a 2x2 matrix B. Perform matrix multiplication using np.dot() or the @ operator.

#### a. np.dot()

In [21]:
A=np.array([[10,20],
            [30,40]])
B=np.array([[50,60],
            [70,80]])
res=np.dot(A,B)
res

array([[1900, 2200],
       [4300, 5000]])

#### b. @ operator

In [22]:
res=A @ B
res

array([[1900, 2200],
       [4300, 5000]])

### 11. Find the transpose of matrix A and matrix B.

In [23]:
a_transpose=A.T
a_transpose

array([[10, 30],
       [20, 40]])

In [24]:
b_transpose=np.transpose(B)
b_transpose

array([[50, 70],
       [60, 80]])

### 12. Create a 3x3 array and a 1D array with 3 elements. Add the 1D array to the 2D array. Explain how broadcasting works in this operation.

In [25]:
a = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]])

b = np.array([10, 20, 30])

In [26]:
result = a + b
result

array([[11, 22, 33],
       [14, 25, 36],
       [17, 28, 39]])

###### Why Broadcasting Works Here
###### NumPy allows broadcasting when:
###### Dimensions match OR
###### One of them is 1
###### Here:
###### a → (3,3)
###### b → becomes (1,3)
###### → The second dimension matches (3 == 3)
###### → First dimension of b is 1, so it can stretch to 3
###### Hence: Valid broadcast.

### 13. Create a 4x4 array of random integers. Find the maximum, minimum, and mean of the entire array.

In [27]:
arr13=np.arange(0,16).reshape(4,4)
arr13

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

#### Find the maximum of the entire array.

In [28]:
arr_max=arr13.max()
arr_max

np.int64(15)

#### Find the minimum of the entire array.

In [29]:
arr_min=arr13.min()
arr_min

np.int64(0)

#### Find the mean of the entire array.

In [30]:
arr_mean=arr13.mean()
arr_mean

np.float64(7.5)

### 14. Find the row-wise and column-wise sums.

In [31]:
arr14=np.arange(1,17).reshape(4,4)
arr14

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

#### a. row-wise sums

In [32]:
row_sum=arr14.sum(axis=1)
row_sum

array([10, 26, 42, 58])

#### b. column-wise sums

In [33]:
column_sum=arr14.sum(axis=0)
column_sum

array([28, 32, 36, 40])

### 15. Generate an array of 10 random integers between 1 and 50.

In [34]:
arr15=np.random.randint(1,50,10)
arr15

array([43, 15, 36, 45,  8, 41,  7, 33, 30, 35], dtype=int32)

### 16. Generate a 5x5 matrix of random floats between 0 and 1.

In [35]:
arr16=np.random.rand(5,5)
arr16

array([[0.94973335, 0.32099748, 0.81393619, 0.33215088, 0.79076406],
       [0.24918172, 0.70847134, 0.445953  , 0.46966938, 0.21007186],
       [0.1337905 , 0.99011702, 0.71183433, 0.82970466, 0.72507665],
       [0.71802642, 0.74686213, 0.97706658, 0.94925634, 0.68884839],
       [0.09873313, 0.30073803, 0.73498798, 0.04623788, 0.8016683 ]])