# Assignment - 1

## 1. Write code to create a 4x3 matrix with values ranging from 2 to 13.

In [1]:
import numpy as np

In [2]:
arr1=np.arange(2, 14).reshape(4,3)
arr1

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10],
       [11, 12, 13]])

## 2. Write code to replace the odd numbers by -1 in the array created by using random.randint( 1 , 50,20)

In [3]:
arr2= np.random.randint(1,50,20)
arr2
np.where(arr2%2==0,arr2,-1)

array([-1, -1, -1, -1, -1, -1, 26, -1, -1, 26, -1, -1, -1, 30, -1, 36, 16,
       -1, 40, 46], dtype=int32)

## 3. Perform the following operations on an array of mobile phones prices 6999, 7500, 11999, 27899, 14999, 9999.

### a. Create a 1d-array of mobile phones prices

In [4]:
arr3=np.array([6999, 7500, 11999, 27899, 14999, 9999])
arr3

array([ 6999,  7500, 11999, 27899, 14999,  9999])

### b. Convert this array to float type

In [5]:
arr3=arr3*1.0
arr3

array([ 6999.,  7500., 11999., 27899., 14999.,  9999.])

In [6]:
arr3.dtype

dtype('float64')

### c. Append a new mobile having price of 13999 Rs. to this array

In [7]:
arr3=np.append(arr3,13999)
arr3

array([ 6999.,  7500., 11999., 27899., 14999.,  9999., 13999.])

### d. Reverse this array of mobile phones prices

In [8]:
arr3=arr3[::-1]
arr3

array([13999.,  9999., 14999., 27899., 11999.,  7500.,  6999.])

### e. Apply GST of 18% on mobile phones prices and update this array.

In [9]:
arr3=arr3*1.18
arr3

array([16518.82, 11798.82, 17698.82, 32920.82, 14158.82,  8850.  ,
        8258.82])

### f. Sort the array in descending order of price

In [10]:
arr3=np.sort(arr3)
arr3

array([ 8258.82,  8850.  , 11798.82, 14158.82, 16518.82, 17698.82,
       32920.82])

In [11]:
arr3=arr3[::-1]
arr3

array([32920.82, 17698.82, 16518.82, 14158.82, 11798.82,  8850.  ,
        8258.82])

### g. What is the average mobile phone price

In [12]:
avg=np.average(arr3)
avg

np.float64(15743.560000000001)

### h. What is the difference b/w maximum and minimum price

In [13]:
diff=np.max(arr3)-np.min(arr3)
diff

np.float64(24662.0)

## 4. Find out the indices of non zero element in given array [1,2,0,0,4,0]

In [14]:
arr4=np.array([1,2,0,0,4,0])
arr4

array([1, 2, 0, 0, 4, 0])

In [15]:
arr4=np.nonzero(arr4)
arr4

(array([0, 1, 4]),)