# Broadcasting/Decleration

In [1]:
import numpy as np

## array()

In [4]:
arr1=np.array([1,2,3,4])
arr1

array([1, 2, 3, 4])

In [5]:
arr1=np.array((1,2,3,4))
arr1

array([1, 2, 3, 4])

In [6]:
arr1=np.array({1,2,3,4})
arr1

array({1, 2, 3, 4}, dtype=object)

In [8]:
arr1=np.array({1:20,2:40,3:50,4:60})
arr1

array({1: 20, 2: 40, 3: 50, 4: 60}, dtype=object)

## arange()

In [9]:
arr1=np.arange(0,11)
arr1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [11]:
arr1=np.arange(0,20,3)
arr1

array([ 0,  3,  6,  9, 12, 15, 18])

## random.randint()

In [12]:
arr1=np.random.randint(1,50,10)
arr1

array([42, 31, 15, 39,  8,  6,  5, 39,  2,  2], dtype=int32)

## linspace()

In [14]:
arr1= np.linspace(1,20)
arr1

array([ 1.        ,  1.3877551 ,  1.7755102 ,  2.16326531,  2.55102041,
        2.93877551,  3.32653061,  3.71428571,  4.10204082,  4.48979592,
        4.87755102,  5.26530612,  5.65306122,  6.04081633,  6.42857143,
        6.81632653,  7.20408163,  7.59183673,  7.97959184,  8.36734694,
        8.75510204,  9.14285714,  9.53061224,  9.91836735, 10.30612245,
       10.69387755, 11.08163265, 11.46938776, 11.85714286, 12.24489796,
       12.63265306, 13.02040816, 13.40816327, 13.79591837, 14.18367347,
       14.57142857, 14.95918367, 15.34693878, 15.73469388, 16.12244898,
       16.51020408, 16.89795918, 17.28571429, 17.67346939, 18.06122449,
       18.44897959, 18.83673469, 19.2244898 , 19.6122449 , 20.        ])

In [15]:
arr1= np.linspace(1,20,10)
arr1

array([ 1.        ,  3.11111111,  5.22222222,  7.33333333,  9.44444444,
       11.55555556, 13.66666667, 15.77777778, 17.88888889, 20.        ])

## random.rand()

In [16]:
arr1=np.random.rand(20)
arr1

array([0.61102549, 0.65638782, 0.2538847 , 0.93671862, 0.28036607,
       0.43172208, 0.92166267, 0.37297677, 0.3714517 , 0.98744684,
       0.40339936, 0.57025952, 0.12232342, 0.07084026, 0.89070442,
       0.55772936, 0.80348911, 0.88392683, 0.07893036, 0.28805833])

## zeros()

In [17]:
arr1=np.zeros(20)
arr1

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0.])

## ones()

In [18]:
arr1=np.ones(20)
arr1

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1.])

## eye()

In [19]:
arr1=np.eye(4)
arr1

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])