## different function

In [1]:
import numpy as np

In [29]:
arr1=np.random.randint(1,50,25)

In [30]:
arr1

array([15, 15, 46,  6,  9, 19, 12, 49, 12, 24, 15, 34, 37, 33, 28,  8, 20,
       32, 26, 25, 12, 13, 15, 22, 34], dtype=int32)

In [31]:
arr1=arr1.reshape(5,5)

In [32]:
arr1

array([[15, 15, 46,  6,  9],
       [19, 12, 49, 12, 24],
       [15, 34, 37, 33, 28],
       [ 8, 20, 32, 26, 25],
       [12, 13, 15, 22, 34]], dtype=int32)

## inbuit fun

In [33]:
arr2=np.random.randint(1,50,15)

In [34]:
arr2.min()

np.int32(1)

In [35]:
arr2.max()

np.int32(44)

In [36]:
arr2.mean()

np.float64(23.8)

In [37]:
arr2.sum()

np.int64(357)

In [38]:
arr2.argmax()

np.int64(0)

In [39]:
arr2.argmin()

np.int64(2)

In [40]:
arr2

array([44, 34,  1,  9, 41, 21, 38, 40,  9, 15,  7, 41, 39,  8, 10],
      dtype=int32)

## Selection

In [41]:
arr2[4]

np.int32(41)

In [42]:
arr2[0:2]

array([44, 34], dtype=int32)

In [43]:
arr2[0:]

array([44, 34,  1,  9, 41, 21, 38, 40,  9, 15,  7, 41, 39,  8, 10],
      dtype=int32)

In [44]:
arr2[:2]

array([44, 34], dtype=int32)

In [45]:
arr2[2:8]

array([ 1,  9, 41, 21, 38, 40], dtype=int32)

In [46]:
arr2[0:9:-1]

array([], dtype=int32)

In [47]:
arr2[0::-1]

array([44], dtype=int32)

In [48]:
arr2[9:0:-1]

array([15,  9, 40, 38, 21, 41,  9,  1, 34], dtype=int32)

In [49]:
arr2[::-1]

array([10,  8, 39, 41,  7, 15,  9, 40, 38, 21, 41,  9,  1, 34, 44],
      dtype=int32)

## 2D Array slicing

In [51]:
arr1

array([[15, 15, 46,  6,  9],
       [19, 12, 49, 12, 24],
       [15, 34, 37, 33, 28],
       [ 8, 20, 32, 26, 25],
       [12, 13, 15, 22, 34]], dtype=int32)

In [53]:
arr1[2,2]

np.int32(37)

In [54]:
arr1[1:4]

array([[19, 12, 49, 12, 24],
       [15, 34, 37, 33, 28],
       [ 8, 20, 32, 26, 25]], dtype=int32)

In [56]:
arr1[2:]

array([[15, 34, 37, 33, 28],
       [ 8, 20, 32, 26, 25],
       [12, 13, 15, 22, 34]], dtype=int32)

In [60]:
arr1[2,2:4]

array([37, 33], dtype=int32)

In [62]:
arr1[3,0:4]

array([ 8, 20, 32, 26], dtype=int32)

In [59]:
arr1[1:4,2]

array([49, 37, 32], dtype=int32)

In [63]:
arr1

array([[15, 15, 46,  6,  9],
       [19, 12, 49, 12, 24],
       [15, 34, 37, 33, 28],
       [ 8, 20, 32, 26, 25],
       [12, 13, 15, 22, 34]], dtype=int32)

In [65]:
arr1[1:4,0:2]

array([[19, 12],
       [15, 34],
       [ 8, 20]], dtype=int32)

In [66]:
arr1[1:,2]

array([49, 37, 32, 15], dtype=int32)

In [67]:
arr1[:4,4]

array([ 9, 24, 28, 25], dtype=int32)

In [68]:
arr1[:,:]

array([[15, 15, 46,  6,  9],
       [19, 12, 49, 12, 24],
       [15, 34, 37, 33, 28],
       [ 8, 20, 32, 26, 25],
       [12, 13, 15, 22, 34]], dtype=int32)

## Conditinal selection

In [69]:
arr2

array([44, 34,  1,  9, 41, 21, 38, 40,  9, 15,  7, 41, 39,  8, 10],
      dtype=int32)

In [70]:
arr2[arr2%2==0]

array([44, 34, 38, 40,  8, 10], dtype=int32)

In [74]:
arr2[arr2>40]

array([44, 41, 41], dtype=int32)

In [75]:
arr2[(arr2%2==0) & (arr2<25)]

array([ 8, 10], dtype=int32)

In [82]:
arr3=np.where(arr2%2==0, 1,-1)
arr3

array([-1, -1,  1, -1, -1,  1, -1, -1,  1,  1, -1,  1, -1, -1,  1])

In [83]:
arr3=np.where(arr2%2==0, arr2,-1)
arr3

array([-1, -1,  8, -1, -1, 10, -1, -1, 34, 38, -1, 40, -1, -1, 44],
      dtype=int32)

In [78]:
arr2.sort()

In [79]:
arr2

array([ 1,  7,  8,  9,  9, 10, 15, 21, 34, 38, 39, 40, 41, 41, 44],
      dtype=int32)

In [81]:
arr1

array([[ 8, 12, 15,  6,  9],
       [12, 13, 32, 12, 24],
       [15, 15, 37, 22, 25],
       [15, 20, 46, 26, 28],
       [19, 34, 49, 33, 34]], dtype=int32)

In [80]:
arr1.sort(axis=0,)
arr1

array([[ 8, 12, 15,  6,  9],
       [12, 13, 32, 12, 24],
       [15, 15, 37, 22, 25],
       [15, 20, 46, 26, 28],
       [19, 34, 49, 33, 34]], dtype=int32)

In [84]:
arr1.sort(axis=1,)
arr1

array([[ 6,  8,  9, 12, 15],
       [12, 12, 13, 24, 32],
       [15, 15, 22, 25, 37],
       [15, 20, 26, 28, 46],
       [19, 33, 34, 34, 49]], dtype=int32)