## Multidimensional array

In [1]:
import numpy as np

### 2D Array

#### 2x4 array

In [3]:
arr1=np.array([[1,2,3,4],[5,6,7,8]])

In [4]:
arr1

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [5]:
arr1.ndim

2

In [6]:
arr1.shape

(2, 4)

### 3x3 Array

In [7]:
arr1=np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])

In [8]:
arr1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## 3D Array

### two 3x3 array

In [9]:
arr1=np.array([[[1,2,3],
                [4,5,6],
               [7,8,9]],
               
               [[9,8,7],
                [6,5,4],
                [3,2,1]
               ]])

In [10]:
arr1

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]],

       [[9, 8, 7],
        [6, 5, 4],
        [3, 2, 1]]])

In [12]:
arr1.ndim

3

In [13]:
arr1.shape

(2, 3, 3)

In [21]:
arr1=np.array([[[1,2,3],
               [4,5,6]],
               
              [[9,8,7],
              [6,5,4]]])

In [22]:
arr1

array([[[1, 2, 3],
        [4, 5, 6]],

       [[9, 8, 7],
        [6, 5, 4]]])

In [23]:
arr1.shape

(2, 2, 3)

In [24]:
arr2=np.array([[1,2,3],
               [4,5,6]])

### Adding array of same size but diff dimension

In [25]:
arr1+arr2

array([[[ 2,  4,  6],
        [ 8, 10, 12]],

       [[10, 10, 10],
        [10, 10, 10]]])