# Numpy Demo

In [2]:
import numpy as np

In [2]:
arr1= np.array([1,2,3,4,5,6,7])
arr2= np.array([8,9,10,11,12,13,14])


In [3]:
arr1

array([1, 2, 3, 4, 5, 6, 7])

In [4]:
arr2

array([ 8,  9, 10, 11, 12, 13, 14])

In [5]:
arr3=arr1+arr2
arr3

array([ 9, 11, 13, 15, 17, 19, 21])

In [6]:
arr4=np.array([1,2,3,4,True,False])

In [7]:
arr4

array([1, 2, 3, 4, 1, 0])

In [10]:
%%time
list1=[x for x in range(1,5001)]
list2=[x for x in range(5001,10001)]
list3=[]
for i, j in zip(list1,list2):
    list3.append(i+j)    

CPU times: total: 0 ns
Wall time: 3.1 ms


In [11]:
%%time
arr1=np.array([x for x in range(1,5001)])
arr2=np.array([x for x in range(5001,10001)])
arr3=arr1+arr2

CPU times: total: 0 ns
Wall time: 2.51 ms


In [13]:
arr5=np.array([1,2,3,"no", True ,None])
arr5

array([1, 2, 3, 'no', True, None], dtype=object)

### check size list and array(numpy)

In [14]:
list1=[1,2,3,4,5]

In [15]:
import sys
sys.getsizeof(list1[0]) * len(list1)

140

In [16]:
arr6= np.array([1,2,3,4,5])

In [17]:
arr6.itemsize*arr6.size

40

## pad

In [4]:
arr1=np.array([1,2,3,4])
arr2=np.array([4,5,6])

In [8]:
np.pad(arr2, (0,7))

array([4, 5, 6, 0, 0, 0, 0, 0, 0, 0])